# Generated by Django 4.1.3 on 2023-01-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='basicinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=60)),
                ('Lastname', models.CharField(max_length=60)),
                ('nickname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
