# Generated by Django 4.1.3 on 2023-01-25 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_basicinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='basicinfo',
            index=models.Index(fields=['Firstname'], name='polls_basic_Firstna_db1b69_idx'),
        ),
        migrations.AddIndex(
            model_name='basicinfo',
            index=models.Index(fields=['Lastname'], name='polls_basic_Lastnam_d76524_idx'),
        ),
        migrations.AddIndex(
            model_name='basicinfo',
            index=models.Index(fields=['nickname'], name='polls_basic_nicknam_6309fc_idx'),
        ),
        migrations.AddIndex(
            model_name='basicinfo',
            index=models.Index(fields=['email'], name='polls_basic_email_b93124_idx'),
        ),
        migrations.AddIndex(
            model_name='basicinfo',
            index=models.Index(fields=['salary'], name='polls_basic_salary_553a3a_idx'),
        ),
    ]
